---
- name: mailutils install
  package:
    name: mailutils
    state: present
  tags: dev_tool_install

- name: iproute2 install
  package:
    name: iproute2
    state: present
  tags: dev_tool_install

- name: iputils-ping install
  package:
    name: iputils-ping
    state: present
  tags: dev_tool_install

- name: nmap install
  package:
    name: nmap
    state: present
  tags: dev_tool_install
  when: ansible_distribution == 'Ubuntu'
