---
- name: mailutils install
  apt:
    pkg: mailutils
    state: present
    update_cache: yes
  tags: dev_tool_install

- name: iproute2 install
  apt:
    pkg: iproute2
    state: present
    update_cache: yes
  tags: dev_tool_install

- name: iputils-ping install
  apt:
    pkg: iputils-ping
    state: present
    update_cache: yes
  tags: dev_tool_install

- name: nmap install
  apt:
    pkg: nmap
    state: present
    update_cache: yes
  tags: dev_tool_install
#  when: ansible_distribution == 'Ubuntu'
