- name: "create group {{ ansible_user_group }}"
  group:
    name: "{{ ansible_user_group }}"

- name: "users exist name:{{ ansible_user_name }} group:{{ ansible_user_group }}"
  user:
    name: "{{ ansible_user_name }}"
    state: present
    password: "{{ ansible_user_password }}"
    group: "{{ ansible_user_group }}"

- name: user join to other group
  user:
    name: "{{ ansible_user.name }}"
    append: yes
    groups: "{{ ansible_user.subgroups }}"

- name: "directory create /home/{{ ansible_user_name }}/.ssh"
  file:
    path: "/home/{{ ansible_user_name }}/.ssh"
    state: directory
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_group }}"
    mode: 0700

- name: "create /home/{{ ansible_user_name }}/.ssh/config"
  template:
    src: "ssh_config.j2"
    dest: "/home/{{ ansible_user_name }}/.ssh/config"
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_group }}"
    mode: 0600

# add key
- name: authorized_keys
  template:
    src: "authorized_keys.j2"
    dest: /home/{{ansible_user_name}}/.ssh/authorized_keys
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_group }}"
    mode: 0600
