# TODO 鍵タイプなのであとで直す
- name: "create directory {{ git.key_dir }}"
  file:
    path: "{{ git.key_dir }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.groups }}"
    mode: 0755

- name: "git key transfer"
  copy:
    src: "/app/key/git_key/rsa_4096"
    dest: "{{ git.key }}"
    owner: root
    group: root
    mode: 0644

- name: "create {{ git.dest }}"
  file:
    path: "{{ git.dest }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.groups }}"
    mode: 0755

- name: "git リフレッシュ"
  become: !!str yes
  become_user: "{{ user.name }}"
  git:
    repo: "{{ git.repository }}"
    dest: "{{ git.dest }}"
    force: !!str yes
    version: master
    key_file: "{{ git.key }}"
    accept_hostkey: !!str yes

- name: "git key delete"
  file:
    path: "{{ git.key }}"
    state: absent
