- include: CentOS.yml
  when: "ansible_os_family == 'RedHat'"

- include: Ubuntu.yml
  when: "ansible_os_family == 'Debian'"

- name: "/var/log/rkhunter directory create"
  file:
    path: "/var/log/rkhunter"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "rkhunter --update"
  ignore_errors: true
  command: rkhunter --update

- name: "rkhunter --propupd"
  command: rkhunter --propupd
