# スクリプト設置場所を作成
- name: "create directory{{ script_dir }}"
  file:
    path: "{{ script_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0777
#    - name: to mail required packages install
#      package:
#        name: "{{ item }}"
#        state: latest
#      with_items:
#        - perl-Email-MIME
#        - perl-JSON
# ssh ログインでメール送る設定
- name: sshrc
  template:
    src: "sshrc.j2"
    dest: "/etc/ssh/sshrc"
    owner: root
    group: root
    mode: 0755
