#    - name: to mail required packages install
#      package:
#        name: "{{ item }}"
#        state: latest
#      with_items:
#        - perl-Email-MIME
#        - perl-JSON

# スクリプト設置場所を作成
- name: "create file {{ ssh_mail_send_trust_list_file }}"
  template:
    src: "ip_trust_list.j2"
    dest: "{{ ssh_mail_send_trust_list_file }}"
    owner: root
    group: root
    mode: 0644
# ssh ログインでメール送る設定
- name: sshrc
  template:
    src: "sshrc.j2"
    dest: "/etc/ssh/sshrc"
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution == "CentOS"

# ssh ログインでメール送る設定
- name: sshrc
  template:
    src: "ubuntu_sshrc.j2"
    dest: "/etc/ssh/sshrc"
    owner: root
    group: root
    mode: 0755
  when: ansible_distribution == "Ubuntu"
