- name: restart samba
  service:
    name: smb
    state: restarted

- name: enable samba
  service:
    name: smb
    enabled: yes

- name: restart nmb
  service:
    name: nmb
    state: restarted

- name: enable nmb
  service:
    name: nmb
    enabled: yes
