# CI Lint tool
# https://gitlab.teamhack.io/ci/lint
---
stages:
  - lint

cache:
  # ブランチ毎にキャッシュする設定
  key: "$CI_COMMIT_REF_NAME"
  untracked: true

## filelint 改行コードを見たりする
filelint:
  stage: lint
  image: toshiclick/gitlab-ci-ansible-centos
  script:
  - filelint .

ansiblelint:
  stage: lint
  image: toshiclick/gitlab-ci-ansible-centos
  script:
    - pip install ansible-lint
    - ansible-lint ./ -c .circleci/.ansible-lint
