- name: get fluentd install shell
  get_url:
    url: "https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh"
    dest: /usr/local/src/install-redhat-td-agent3.sh
    mode: 0755

- name: run fluentd install shell
  command: bash /usr/local/src/install-redhat-td-agent3.sh
  notify:
  - restart fluentd
  - enable fluentd

- name: custom fluentd Plugin set
  template:
    src: "filter_ngrep.rb.j2"
    dest:  /etc/td-agent/plugin/filter_ngrep.rb
    owner: root
    group: root
    mode: 0644
  notify:
  - restart fluentd

# よく使うプラグイン導入
- name : plugin To Use Often
  command: td-agent-gem install {{ item }}
  with_items:
  - fluent-plugin-rewrite-tag-filter
  - fluent-plugin-elasticsearch
  - fluent-plugin-record-reformer
  - fluent-plugin-cloudwatch-logs
  - fluent-plugin-ec2-metadata
  - fluent-plugin-s3
  - fluent-plugin-slack
  - fluent-plugin-rewrite
  - fluent-plugin-tail-ex
  - fluent-plugin-forest
  - fluent-plugin-google-cloud
  notify:
  - restart fluentd

# これはプロジェクトごとにあとで書き換える想定。
- name: default td-agent.conf set
  template:
    src: "td-agent.conf.j2"
    dest:  /etc/td-agent/td-agent.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart fluentd
