- name: get fluentd install shell
  get_url:
    url: "https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh"
    dest: /usr/local/src/install-redhat-td-agent3.sh
    mode: 0755

- name: run fluentd install shell
  command: bash /usr/local/src/install-redhat-td-agent3.sh
  notify:
  - restart fluentd

- name: enable fluentd
  service:
    name: td-agent
    enabled: yes

- name: custom fluentd Plugin set
  template:
    src: "filter_ngrep.rb.j2"
    dest:  /etc/td-agent/plugin/filter_ngrep.rb
    owner: root
    group: root
    mode: 0644
  notify:
  - restart fluentd

# よく使うプラグイン導入
- name : plugin To Use Often
  command: td-agent-gem install {{ item }}
  with_items:
  - fluent-plugin-rewrite-tag-filter
  - fluent-plugin-elasticsearch
  - fluent-plugin-cloudwatch-logs
  - fluent-plugin-slack
  - fluent-plugin-tail-ex
  notify:
  - restart fluentd

# これはプロジェクトごとにあとで書き換える想定。
- name: default td-agent.conf set
  template:
    src: "td-agent.conf.j2"
    dest:  /etc/td-agent/td-agent.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart fluentd

- name: "td agent by can read to logrotate setting"
  template:
    src: "syslog.j2"
    dest: /etc/logrotate.d/syslog
    owner: root
    group: root
    mode: 0644

- name: "td agent by can read to logrotate setting"
  template:
    src: "syslog.j2"
    dest: /etc/logrotate.d/syslog
    owner: root
    group: root
    mode: 0644

- name: "td agent by can read to maillog"
  file:
    path: /var/log/maillog
    owner: root
    group: root
    mode: 0644

- name: "td agent by can read to messages"
  file:
    path: /var/log/messages
    owner: root
    group: root
    mode: 0644

- name: "td agent by can read to secure"
  file:
    path: /var/log/secure
    owner: root
    group: root
    mode: 0644
