- name: get RedHat fluentd install shell
  get_url:
    url: "https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh"
    dest: /usr/local/src/install-redhat-td-agent3.sh
    mode: 0755
  when: "ansible_os_family == 'RedHat'"

- name: run RedHat fluentd install shell
  shell: bash /usr/local/src/install-redhat-td-agent3.sh
  when: "ansible_os_family == 'RedHat'"

- name: get Debian fluentd install shell
  get_url:
    url: "https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent3.sh"
    dest: /usr/local/src/install-ubuntu-xenial-td-agent3.sh
    mode: 0755
  when: "ansible_os_family == 'Debian'"

- name: run Debian fluentd install shell
  shell: bash /usr/local/src/install-ubuntu-xenial-td-agent3.sh
  when: "ansible_os_family == 'Debian'"

- name: enable fluentd
  service:
    name: td-agent
    enabled: yes

- name: custom fluentd Plugin set
  template:
    src: "filter_ngrep.rb.j2"
    dest:  /etc/td-agent/plugin/filter_ngrep.rb
    owner: root
    group: root
    mode: 0644
  notify:
  - restart fluentd

# よく使うプラグイン導入
- name : plugin To Use Often
  command: td-agent-gem install {{ item }}
  with_items:
  - fluent-plugin-rewrite-tag-filter
  - fluent-plugin-elasticsearch
  - fluent-plugin-cloudwatch-logs
  - fluent-plugin-slack
  - fluent-plugin-tail-ex
  - fluent-plugin-mail
