# パッケージアップデート------
# CentOS向け設定
- block:
  - name: packages update
    package:
      name: "*"
      state: latest
  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"

# Debian・Ubuntu向け設定
- block:
  - name: Updating host using apt
    apt:
      update_cache: no
      upgrade: dist
      state: latest

  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"
