# パッケージアップデート------
# CentOS向け設定
- block:
  - name: packages update
    package:
      name: "*"
      state: present
  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"

# Debian・Ubuntu向け設定
- block:
  - name: delete apt lock files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/lib/apt/lists/lock
      - /var/cache/apt/archives/lock

  - name: Updating apt
    shell: apt update -y --allow-releaseinfo-change

  - name: install aptitude
    apt:
      name: aptitude
      update_cache: yes
      cache_valid_time: 3600

  - name: Updating host using apt
    apt:
      name: "*"
      upgrade: yes
      state: present
      update_cache: yes
      cache_valid_time: 3600
    ignore_errors: true
  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"
