# パッケージアップデート------
# CentOS向け設定
- block:
  - name: packages update
    package:
      name: "*"
      state: present
  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"

# Debian・Ubuntu向け設定
- block:
  - name: install aptitude
    apt:
      pkg: aptitude

  - name: apt-get clean
    shell: apt-get clean
    ignore_errors: true

  - name: Updating host using apt
    apt:
      upgrade: yes
      state: present
      update_cache: yes
      cache_valid_time: 3600
  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"
