- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

# 標準出力をSlackに通知するシェルを配置する
- name: "{{ script_dir }}/stdout_to_slack.sh set"
  template:
    src: "stdout_to_slack.sh"
    dest: "{{ script_dir }}/stdout_to_slack.sh"
    owner: root
    group: root
    mode: 0755
