- include: CentOS.yml
  when: "ansible_os_family == 'RedHat'"

- include: Ubuntu.yml
  when: "ansible_os_family == 'Debian'"

# スクリプト設置場所を作成
- name: "create directory{{ script_dir }}"
  file:
    path: "{{ script_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0777

# 標準出力をSlackに通知するシェルを配置する
- name: "{{ bin_dir }}/stdout_to_slack.sh set"
  template:
    src: "stdout_to_slack.sh"
    dest: "{{ bin_dir }}/stdout_to_slack.sh"
    owner: root
    group: root
    mode: 0755
