# CentOS向け設定
- block:
  # sudo の設定
  - name: "/etc/sudoers"
    template:
      src: "sudoers.j2"
      dest: "/etc/sudoers"
      owner: root
      group: root
      mode: 0440
    tags: secure

  # suの制限-----------------------------------------------------------------------------------------
  - name: /etc/pam.d/su
    template:
      src: "su.j2"
      dest: "/etc/pam.d/su"
      owner: root
      group: root
      mode: 0644
    tags: secure
  # hosts.allow -----------------------------------------------------------------------------------------
  - name: "/etc/hosts.allow"
    template:
      src: "hosts.allow.j2"
      dest: "/etc/hosts.allow"
      owner: root
      group: root
      mode: 0644
    tags: secure

  # hosts.deny -----------------------------------------------------------------------------------------
  - name: "/etc/hosts.deny"
    template:
      src: "hosts.deny.j2"
      dest: "/etc/hosts.deny"
      owner: root
      group: root
      mode: 0644
    tags: secure
  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"

# Debian・Ubuntu向け設定
- block:
  # sudo の設定
  - name: "/etc/sudoers"
    template:
      src: "ubuntu_sudoers.j2"
      dest: "/etc/sudoers"
      owner: root
      group: root
      mode: 0440
    tags: secure
  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"
