---
# tasks file for virtualbox (CentOS specific)

- name: Configure Oracle VirtualBox YUM repository
  template: >
    src=virtualbox.repo.j2
    dest=/etc/yum.repos.d/virtualbox.repo
    owner=root
    group=root
    mode=0644
  tags: virtualbox

- name: kernel-devel install
  package:
    name: kernel-devel
    state: present

- name: Install VirtualBox packages
  yum:
    name: "{{ virtualbox_packages }}"
    state: present
  with_items: {{ virtualbox_packages }}
  tags: virtualbox

- name: VirtualBox rcvboxdrv setup
  shell: /sbin/rcvboxdrv setup
