---
# tasks file for virtualbox

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: virtualbox

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: virtualbox

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: virtualbox
