- name: restart iptables
  service:
    name: iptables
    state: restarted
    enabled: !!str yes

- name: restart ip6tables
  service:
    name: ip6tables
    state: restarted
    enabled: !!str yes
