- name: get RedHat fluentd install shell
  get_url:
    url: "https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh"
    dest: /usr/local/src/install-redhat-td-agent3.sh
    mode: 0755
  tags: fluentd

- name: run RedHat fluentd install shell
  shell: bash /usr/local/src/install-redhat-td-agent3.sh
  tags: fluentd
