- name: get Debian fluentd install shell
  get_url:
    url: "https://toolbelt.treasuredata.com/sh/install-ubuntu-xenial-td-agent3.sh"
    dest: /usr/local/src/install-ubuntu-xenial-td-agent3.sh
    mode: 0755
  tags: fluentd

- name: run Debian fluentd install shell
  shell: bash /usr/local/src/install-ubuntu-xenial-td-agent3.sh
  tags: fluentd

- name: make install
  package:
    name: make
    state: present
  tags: fluentd
