---
- name: homebrew update
  become: false
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: homebrew tap
  become: false
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew_taps }}'

- name: homebrew packages install
  become: false
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  with_items: '{{ homebrew_packages }}'
