#cache_version_keys: &cache_version_keys
#  CACHE_VERSION_OF_PROJECT_DEPS: v2
#  CACHE_VERSION_OF_DANGER_CACHE: v1

#cache_keys:
#  danger_cache:
#    primary: &primary_key_of_danger_cache danger-cache-{{ checksum "~/CACHE_VERSION_OF_DANGER_CACHE" }}-{{ checksum "~/danger_cache" }}
#    keys: &all_keys_of_danger_cache
#      - *primary_key_of_danger_cache
#      - danger-cache-{{ checksum "~/CACHE_VERSION_OF_DANGER_CACHE" }}-
version: 2.1
executors:
  # ここに好きな名前で executor を定義できる
  default:
    working_directory: ~/repo
    docker:
      - image: python:2.7
jobs:
  setup:
    executor: # name で使いたい executor を指定する
      name: default
    steps:
  - checkout
  - run: pip install -r ./.circleci/requirements.txt
  - run: ansible-lint ./**/*.yml -c .circleci/.ansible-lint
