- name: libvirt install
  package:
    name: libvirt
    state: present
  notify:
    - enable libvirt
    - restart libvirt

- name: disable libvirtd
  service:
    name: libvirtd
    enabled: !!str no

# GUI操作用にvirt-managerを入れる
- name: virt-manager install
  package:
    name: virt-manager
    state: present

# CUI操作用にvirt-installを入れる
- name: virt-install install
  package:
    name: virt-install
    state: present

# ブリッジを有効にするためにbridge-utilsをインストール
- name: bridge-utils install
  package:
    name: bridge-utils
    state: present

# virtのデフォルト設定を削除する
- name: Delete virt default net
  shell: virsh net-destroy default

# virtのデフォルト設定を削除する
- name: Delete virt default
  shell: virsh net-undefine default

# 仮想ブリッジの自動起動抑止
- name: Disable virt default net autostart
  shell: virsh net-autostart default --disable
