# パッケージアップデート------
- block:
  - name: packages update
    package:
      name: "*"
      state: latest
    when: "ansible_os_family == 'RedHat'"
  # CentOS向けここまで
  when: "ansible_os_family == 'RedHat'"

# Debian・Ubuntu向け設定
- block:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  # Debian・Ubuntu向け設定ここまで
  when: "ansible_os_family == 'Debian'"
