# 実行したい場合はvarファイルのservice:に下記var足してください
# service:
#   docker:
#     compose_dir: "/export/www/i-tenpo.com/docker/dev_service"
- name: restart iptables
  service:
    name: iptables
    state: restarted
    enabled: !!str yes

- name: restart docker
  service:
    name: docker
    state: restarted

- name: "do {{ service.docker.compose_dir }}/docker-compose pull"
  shell: /usr/local/bin/docker-compose pull
  args:
    chdir: "{{ service.docker.compose_dir }}"

- name: "do {{ service.docker.compose_dir }}/docker-compose build --no-cache"
  shell: /usr/local/bin/docker-compose build --no-cache
  args:
    chdir: "{{ service.docker.compose_dir }}"

- name: "do {{ service.docker.compose_dir }}/docker-compose down"
  shell: /usr/local/bin/docker-compose down
  args:
    chdir: "{{ service.docker.compose_dir }}"

- name: "do {{ service.docker.compose_dir }}/docker-compose up -d --force-recreate"
  shell: /usr/local/bin/docker-compose up -d --force-recreate
  args:
    chdir: "{{ service.docker.compose_dir }}"
