- name: restart iptables
  service:
    name: iptables
    state: restarted
    enabled: !!str yes
  notify:
  - restart docker

- name: restart ip6tables
  service:
    name: ip6tables
    state: restarted
    enabled: !!str yes

- name: restart docker
  service:
    name: docker
    state: restarted
