---
- name: xrdp install
  package:
    name: xrdp
    state: present
  notify:
    - enable xrdp
    - restart xrdp

- name: install xserver-xorg-core
  apt:
    pkg: xserver-xorg-core
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: install xorgxrdp
  apt:
    pkg: xorgxrdp
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: install tightvncserver
  apt:
    pkg: tightvncserver
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: ubuntu-desktop install
  package:
    name: ubuntu-desktop
    state: present

- name: install tasksel
  apt:
    pkg: tasksel
    state: present
    update_cache: yes
    cache_valid_time: 3600

# ログイン後にエラー出るので対応
- name:
  lineinfile:
    path: /etc/xrdp/xrdp.ini
    regexp: '^new_cursors=true'
    line: 'new_cursors=false'

  chmod 711 /etc/ssl/private/
  chmod 644 /etc/ssl/private/ssl-cert-snakeoil.key
