---
# ダークモードにする
- name: set AppleInterfaceStyle
  osx_defaults:
    host: "NSGlobalDomain"
    key: "AppleInterfaceStyle"
    type: string
    value: Dark

- name: 'Dock tilesize'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'tilesize'
    type: 'float'
    value: "{{ mac_dock_icon_size }}"
    state: 'present'
  notify: 'restart dock'

- name: 'Dock autohide'
  osx_defaults:
    domain: 'com.apple.dock'
    key: 'autohide'
    type: 'bool'
    value: "{{ mac_dock_auto_hide }}"
    state: 'present'
  notify: 'restart dock'

# Dock - スペース表示高速化
# defaults write com.apple.dock workspaces-swoosh-animation-off -bool yes
- name: workspaces-swoosh-animation-off
  osx_defaults:
    domain: com.apple.dock
    key: workspaces-swoosh-animation-off
    type: boolean
    value: true
    state: present
  notify: 'restart dock'

# キーリピートの速度を爆速に
# キーリピート検知待ち時間
- name: key repeat detection waiting time
  osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: "{{ mac_key_repeat_waiting_time }}"
    state: present

# キーリピート間隔時間
- name: key repeat interval time
  osx_defaults:
    key: KeyRepeat
    type: int
    value: "{{ mac_key_repeat_interval_time }}"
    state: present

# バッテリー残量設定
- name: battery balance amount preference
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: YES
    state: present

# 時刻表示設定
- name: time display preference
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "M\\U6708d\\U65e5(EEE)  H:mm:ss"
    state: present

# トラックパッド右クリックの有効化
- name: truck pad right-click activation
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 2
    state: present

# トラックパッドタップの有効化
- name: truck pad tap activation
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1
    state: present

# ライブ変換の無効化
- name: live converting invalidation
  osx_defaults:
    domain: com.apple.inputmethod.Kotoeri
    key: JIMPrefLiveConversionKey
    type: int
    value: 0
    state: present

- name: config sudoers
  become: yes
  become_user: root
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin\s+ALL'
    line: '%admin ALL = (ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

###############################################################################
# Finder
###############################################################################
- name: Finder Show dotfiles
  osx_defaults:
    domain: "com.apple.finder"
    key: "AppleShowAllFiles"
    type: bool
    value: true
  notify: restart Finder

- name: Finder Show Pathbar
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowPathbar"
    type: bool
    value: true
  notify: restart Finder

- name: Finder Show StatusBar
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowStatusBar"
    type: bool
    value: true
  notify: restart Finder

# ネットワーク接続時の.DS_Store作成を抑制
# defaults write com.apple.desktopservices DSDontWriteNetworkStores true
- name: DSDontWriteNetworkStores
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

# スクリーンショットのファイル名から日本語を削除
- name: screenshot filename from Japanese deletion
  osx_defaults:
    domain: "com.apple.screencapture"
    key: "name"
    type: string
    value: ""

# スワイプを普通の向きにする
- name: make facing normal swipe
  osx_defaults:
    key: "com.apple.swipescrolldirection"
    type: bool
    value: false

# 保存先を指定するダイアログを簡易的なものにしない
- name: save target specify dialog simple do not
  osx_defaults:
    key: "NSNavPanelExpandedStateForSaveMode"
    type: bool
    value: true
