- name: restart postfix
  service:
    name: postfix
    state: restarted
  when:
    - runner is undefined

- name: enable postfix
  service:
    name: postfix
    enabled: !!str yes
  when:
    - runner is undefined
