# ansible install
- name: ansible install
  package:
    name: ansible
    state: present

# https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg
## hostキーのチェックしないように修正
- name: /etc/ansible/ansible.cfg
  template:
    src: "ansible.cfg"
    dest: "/etc/ansible/ansible.cfg"
    owner: root
    group: root
    mode: 0644
