kind: Deployment

apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
#              value: (NFS サーバのホスト名: host_d など)
              value: {{ machine_hostname }}
            - name: NFS_PATH
#              value: (マウントするパス: /opt/nfs など)
              value: {{ nfs_shared_directory }}
      volumes:
        - name: nfs-client-root
          nfs:
            server: {{ machine_hostname }}
            path: {{ nfs_shared_directory }}
