---
homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_packages:
#  - name: direnv
#  - name: fzf
  - name: git
#  - name: python3
#  - name: terraform
#  - name: the_silver_searcher
#  - name: tig
#  - name: tmux
  - name: bash-completion
  - name: binutils
  - name: coreutils
  - name: findutils
  - name: grep
  - name: gnu-sed
  - name: gnu-tar
  - name: gzip
  - name: gawk
  - name: tree
#  - name: bettertouchtool
  - name: mas
