---
# tasks file for ufw (Ubuntu specific)
- name: Install ufw packages
  apt:
    pkg: ufw
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: ufw
  notify:
    - enable ufw
    - restart ufw
