- name: postfix install
  package:
    name: postfix
    state: latest
  notify:
  - enable postfix
  - restart postfix

- name: main.cf set
  template:
    src: "main.cf.j2"
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart postfix

- name: aliases set
  template:
    src: "aliases.j2"
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
  notify:
  - newaliases
  - restart postfix

- name: virtual_maps set
  template:
    src: "virtual_maps.j2"
    dest: /etc/postfix/virtual_maps
    owner: root
    group: root
    mode: 0644
  notify:
  - restart postfix

# root宛メールをslackに通知するシェル配置
- block:
  - name: "create directory{{ directory.root_dir }}"
    file:
      path: "{{ directory.root_dir }}"
      state: directory
      owner: root
      group: root
      mode: 0777

  - name: "create directory{{ directory.root_dir }}/bin"
    file:
      path: "{{ directory.root_dir }}/bin"
      state: directory
      owner: root
      group: root
      mode: 0777

  - name: to mail required packages install
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - perl-Email-MIME
    - perl-JSON

  - name: mail2slack sh set
    template:
      src: "mail2slack.j2"
      dest: "{{ directory.root_dir }}/bin/mail2slack"
      owner: root
      group: root
      mode: 0755
  when: send_slack == 'true'

# ssh ログインでメール送る設定
- name: sshrc
  template:
    src: "sshrc.j2"
    dest: "/etc/ssh/sshrc"
    owner: root
    group: root
    mode: 0755
