- name: "install ibus-kkc"
  package:
    name: "ibus-kkc"
    state: latest

- name: "install vlgothic-*"
  package:
    name: "vlgothic-*"
    state: latest

# 日本語の設定
# - name: "set-locale"
#  command: localectl set-locale LANG=ja_JP.UTF-8

- name: "localedef"
  command: localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

- name: "set ja_JP to /etc/locale.conf"
  command: bash -c "echo 'LANG="ja_JP.UTF-8"' > /etc/locale.conf"

- name: "set ja_JP"
  command: bash -c "source /etc/locale.conf"
